// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/platform-landing/Improved.tsx": () => import("../components/mockups/platform-landing/Improved.tsx"),
  "./components/mockups/city-logo/AustinLogoOptions.tsx": () => import("../components/mockups/city-logo/AustinLogoOptions.tsx")
};
